#!/usr/bin/env bash

BASE_COLLECTION_PATH="/must-gather"
# generate /must-gather/version file
. version
echo "must-gather-node" > ${BASE_COLLECTION_PATH}/version
version >> ${BASE_COLLECTION_PATH}/version

gather_ocp
gather_nodes
